import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;

public class secondTopButton extends BasePage{
    Variables variables;
    public secondTopButton(WebDriver driver) {
        super(driver);
        variables = new Variables();
    }
    public void secondTry(){
        waits("xpath",variables.topmenu2);
        find("xpath",variables.topmenu2);
        click("xpath",variables.topmenu2);
        waits("css",variables.headerMenu2);
        screenSchot(find("css",variables.headerMenu2).getAttribute("innerHTML"));
        scroll(350);
        sendText("css",variables.whereYouSee,"Gaziantep");
        waits("xpath",variables.chooseCity);
        click("xpath",variables.chooseCity);
        waits("css",variables.headerMenuCity);
        screenSchot(find("css",variables.headerMenuCity).getAttribute("innerHTML"));
        scroll(150);
        waits("xpath",variables.fromCity);
        sendAndKeys("xpath",variables.fromCity,"Gaziantep", Keys.ENTER);
        waits("clickxpath",variables.toCity);
        sendAndKeys("xpath",variables.toCity,"İstanbul",Keys.ENTER);
        find("xpath",variables.fromDate);
        waits("xpath",variables.fromDate);
        click("clickxpath",variables.fromDate);
        waits("clickxpath",variables.nextMonth);
        click("xpath",variables.nextMonth);
        waits("clickcss",variables.firstDate);
        click("css",variables.firstDate);
        waits("css",variables.secondDate);
        click("css",variables.secondDate);
        waits("clickcss",variables.passengers);
        click("css",variables.passengers);
        click("css",variables.passengers);
        waits("clickcss",variables.searchFly);
        screenSchot(find("css",variables.searchFly).getText());
        click("css",variables.searchFly);
        waits("css",variables.afterSearchFly);
        scroll(300);
        waits("clickxpath",variables.fromTicket);
        click("xpath",variables.fromTicket);
        scroll(300);
        waits("clickxpath",variables.fromButtonTicket);
        click("xpath",variables.fromButtonTicket);
        waits("clickcss",variables.basicTicket);
        click("css",variables.basicTicket);
        waits("css",variables.firstTicket);
        scroll(400);
        waits("clickxpath",variables.fromTicket);
        click("xpath",variables.fromTicket);
        scroll(400);
        waits("clickxpath",variables.fromButtonTicket);
        click("xpath",variables.fromButtonTicket);
        click("css",variables.basicTicket);
        waits("css",variables.firstTicket);
        waits("css",variables.firstTicket);
        scroll(150);
        screenSchot(find("css",variables.whereArea).getText());
        waits("css",variables.continueForTicket);
        click("css",variables.continueForTicket);
        waits("css",variables.passengerInf);
        scroll(700);
        waits("css",variables.firstName);
        sendText("css",variables.firstName,"Aliye");
        sendText("css",variables.lastName,"Karakoyun");
        sendText("css",variables.birthDate,"04.07.1923");
        waits("clickxpath",variables.gender);
        click("xpath",variables.gender);
        screenSchot(find("xpath","//main/div/div[@class='font-semibold text-secondary-500']").getText());
        scroll(250);
        waits("css",variables.nationalId);
        sendText("css",variables.nationalId,"34057498336");
        waits("css",variables.passengerPhone);
        scroll(300);
        sendText("css",variables.passengerPhone,"5065555578");
        waits("css",variables.passengerContact);
        scroll(250);
        waits("css",variables.contactMail);
        sendText("css",variables.contactMail,"aliyekarakoyun@gmail.com");
        waits("css",variables.continueForTicket);
        screenSchot(find("xpath","//div[5]/div/div[@class='font-semibold text-secondary-500']").getText());
        click("css",variables.continueForTicket);
        waits("xpath",variables.chooseComfortable);
        scroll(300);
        waits("xpath",variables.wantChoose);
        screenSchot(find("xpath",variables.wantChoose).getText());
        click("xpath",variables.wantChoose);
        waits("xpath",variables.wantMoreService);
        scroll(200);
        waits("xpath",variables.wantMoreService);
        screenSchot(find("xpath",variables.wantMoreService).getText());
        click("xpath",variables.wantMoreService);
        waits("xpath",variables.paySummaryPage);
        scroll(150);
        screenSchot(find("xpath",variables.paySummary).getText());
        waits("css",variables.continueForTicket);
        click("css",variables.continueForTicket);
        waits("clickcss",variables.acceptRule);
        onButton(find("css",variables.acceptRule));
        scroll(200);
        screenSchot("Genel Kurallar");
        click("css",variables.acceptRule);
        waits("clickcss",variables.continueForTicket);
        click("css",variables.continueForTicket);
        waits("css",variables.payPage);
        waits("clickxpath",variables.creditCard);
        click("xpath",variables.creditCard);
        waits("css",variables.cardNumber);
        sendText("css",variables.cardNumber,"123456789123456");
        waits("clickxpath",variables.cardLastDate);
        click("xpath",variables.cardLastDate);
        waits("css",variables.lastDay);
        click("css",variables.lastDay);
        waits("clickxpath",variables.chooseLastYear);
        click("xpath",variables.chooseLastYear);
        waits("clickcss",variables.lastYear);
        click("css",variables.lastYear);
        scroll(250);
        waits("xpath",variables.liveCountryClick);
        click("xpath",variables.liveCountryClick);
        waits("css",variables.liveCountry);
        click("css",variables.liveCountry);
        waits("clickcss",variables.liveCity);
        sendText("css",variables.liveCity,"Gaziantep");
        waits("css", variables.address);
        sendText("css",variables.address,"deneme-deneme");
        scroll(200);
        waits("css",variables.chkAccept);
        click("css",variables.chkAccept);
        waits("xpath",variables.acceptPay);
        click("xpath",variables.acceptPay);
        screenSchot(find("css","div[id='creditCard_cardNumber_help'] div").getText());
        scroll(0);
        waits("clickxpath",variables.creditCard);
        click("xpath",variables.creditCard);
        waits("clickxpath",variables.bkmExpress);
        click("xpath",variables.bkmExpress);
        screenSchot(find("xpath","//div[@data-testid='payment-catalog']//div[2]/div[@class='payment-title'][1]").getText());
        waits("clickxpath",variables.acceptPay);
        click("xpath",variables.acceptPay);
        waits("clickcss","a[id='cancelPayment']");//sorun burada
        screenSchot("bkmExpress");
        System.out.println("bkmExpress: " + driver.getCurrentUrl());
        click("css","a[id='cancelPayment']");
        waits("clickcss",variables.continueForTicket);
        click("css",variables.continueForTicket);
        waits("clickxpath",variables.otherPay);
        click("xpath",variables.otherPay);
        screenSchot(find("xpath","//div[@data-testid='payment-catalog']//div[3]/div[@class='payment-title'][1]").getText());
        waits("clickxpath",variables.acceptPay);
        click("xpath",variables.acceptPay);
        waits("css","a[id='header-online-unionpay-href-id2']");
        screenSchot(find("css","a[id='header-online-unionpay-href-id2']").getText());

    }
}
