public class Variables {
    String topmenu1 = "//div[@class='menu-items']/span[1]/a";
    String title1 = "h1[class='hero-cap']";
    String allTopMenu = "div[class='sub-block'] a";
    String topmenu2 = "//div[@class='menu-items']/span[2]/a";
    String headerMenu2 = "h1[class='hero-cap']";
    String whereYouSee = "div[class='grid'] div span div input";
    String chooseCity = "//div[@class='p-dropdown-items-wrapper']/ul/li[29]";
    String headerMenuCity = "h1[class='city-guide hero-cap']";
    String fromCity = "//div[@class='p-card-body px-16 sm:px-24']/div/div[2]/div[1]/div/div[1]//input";
    String toCity = "//div[@class='p-card-body px-16 sm:px-24']/div/div[2]/div[1]/div/div[2]//input";
    String fromDate = "//div[@class='flex gap-3']/div[1]//input";
    String nextMonth = "//div[@class='dp__menu_inner dp__flex_display']/div[2]/div[1]/div/span[2]";
    String firstDate = "div[id='2024-10-11'] div";
    String secondDate = "div[id='2024-10-13'] div";
    String passengers = "div[class='input-with-icon']";
    String searchFly = "button[class='aj-button primary large search-button']";
    String afterSearchFly = "div[class='p-card p-component p-16 lg:p-32']";
    String fromTicket = "//div/div[@class='p-accordion p-component'][1]/div[1]/div/a//div[@class='flex justify-content-center align-items-center accordion-chevron-container']";
    String fromButtonTicket = "//div[@class='p-accordion-content border-none']/div/div/div[2]/div/div[2]/button";
    String basicTicket = "button[class='aj-button secondary large w-full']";
    String firstTicket = "div[class='p-card-content pb-0']";
    String whereArea = "div[class='font-semibold text-secondary-500']";
    String continueForTicket = "div[class='details-container minimize'] button";
    String passengerInf = "div[class='passenger-login-container mt-48 h-full']";
    String firstName = "div[class='col-12 lg:col-8 xl:col-6 p-0'] input[name='firstName']";
    String lastName = "div[class='col-12 lg:col-8 xl:col-6 p-0'] input[name='lastName']";
    String birthDate = "input[id='birthDate']";
    String gender = "//div[@class='flex gap-5']/div[1]/div[@data-pc-name='radiobutton']";
    String nationalId = "input[id='nationalId']";
    String passengerPhone = "input[name='passengerPhone-phone-number']";
    String passengerContact = "a[id='pv_id_38_0_header_action']";
    String contactMail = "input[name='email']";
    String chooseComfortable = "//main[@class='seat-selection pb-with-stickybar']/div[2]/div[1]";
    String wantChoose = "//div[@id='pv_id_42_content']/div[3]";
    String moreService = "//main[@class='pb-with-stickybar']/div[2]/div[1]";
    String wantMoreService = "//div[@class='flex justify-content-end align-items-center my-16']/div/span[1]";
    String paySummary = "//main[@class='pb-with-stickybar']/div[2]/div[1]";
    String paySummaryPage = "//section[@class='journey-info mb-48']/div[@class='shape-title justify-content-end align-items-center gap-2 mt-24'][1]";
    String acceptRule = "div[class='p-checkbox-box']";
    String payPage = "div[class='ant-card-body']";
    String creditCard = "//div[@class='ant-col ant-col-xs-24']/div/div[1]/div/div";
    String cardNumber = "input[id='creditCard_cardNumber']";
    String cardLastDate = "//div[@class='ant-col ant-col-xs-14']/div/div[1]//div[@class='ant-select-selector']";
    String lastDay = "div[title='01']";
    String chooseLastYear = "//div[@class='ant-col ant-col-xs-14']/div/div[2]//div[@class='ant-select-selector']";
    String lastYear = "div[title='26']";
    String liveCountryClick = "//form[@id='creditCard']/div[3]/div/div[2]/div[1]/div[1]/div/div[2]/div/div/div/div/span/input";
    String liveCountry = "div[title='Türkiye']";
    String liveCity = "input[id='creditCard_city']";
    String address = "textArea[id='creditCard_streetAddressA']";
    String chkAccept = "span[class='ant-checkbox-inner']";
    String acceptPay = "//div[@class='ant-row']//div[1]/div[@class='ant-col']/button";
    String bkmExpress = "//div[@class='ant-col ant-col-xs-24']/div/div[2]/div/div";
    String otherPay = "//div[@class='ant-col ant-col-xs-24']/div/div[3]/div/div";
    String topMenu3 = "//div[@class='menu-items']/span[3]/a";
    String sssAll = "div[class='block faq-block lighter-bg'] a";
    String loginButton = "div[id='header-login'] button";
    String wantMember = "div[class='col-12 mt-8 signup-button-container'] button";
    String memberName = "input[name='firstName']";
    String memberLastName = "input[name='lastName']";
    String memberBirth = "input[name='dateOfBirth']";
    String memberGender = "//div[@class='flex gap-5']/div[2]";
    String memberPhone = "input[name='username-phone-number']";
    String memberMail = "input[name='email']";
    String memberPassword = "div[name='password'] input";
    String showPassword = "div[name='password'] button";
    String acceptMemberRules = "div[class='grid mt-12'] div[class='p-checkbox p-component']";
    String signUp = "button[class='aj-button primary large w-full']";
    String signIn = "button[class='aj-button tertiary large w-full']";
    String closeScreen = "button[class='p-overlaypanel-close p-link login-form-close-button']";
    String acceptCookie = "button[class='aj-button primary medium']";
    String signInMeberPhone = "div[class='login-form grid m-0'] input[name='username-phone-number']";
    String singInPassword = "div[class='login-form grid m-0'] div[name='password'] input";
    String seePassword = "div[class='login-form grid m-0'] div[name='password'] button";
    String rememberMe = "//div[@class='col-12 mt-8 login-remember-forgot-container flex justify-content-between align-items-center']/div";
    String signInButton = "div[class='login-form grid m-0'] button[class='aj-button primary large w-full']";
    String forgetPasswordMail = "div[class='aj-input'] input[name='email']";
    String sendMail ="button[class='aj-button primary large w-full']";
    String forgetPassword = "div[class='login-form grid m-0'] button[class='p-button p-component p-button-link aj-font-secondary']";
}
